server:
  port: 8888

management:
  context-path: /manage
  
logging:
  level:
#   com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    

  
encrypt: 
  key: platform_service_security_key
  

spring: 
  application:
    name: configuration
  jmx: 
    enabled: false
  cloud: 
    config:
      server:
        prefix: cfg
        git:
          uri: https://github.com/A491382/configuration-repo.git
          username: A491382
          password: Qazz7410

