jsondoc:
  version: 1.2.17
  base-path: http://localhost:8888/cfg/
  packages: org.springframework.cloud.config.server.environment,org.springframework.cloud.config.server.encryption
  playground-enabled: true
  display-method-as: URI
  
  
  
  